### ISSUE TITLE
Middle Mouse Button to grab and scroll through level

### ISSUE THREAD

**Issue by Superjustinbros** [Violet-CLM/MLLE#104]
Currently, the middle mouse button does nothing in the editor, so I thought implementing a feature to pan through the level by holding the middle mouse button down and moving the mouse around the window would be useful for editing larger levels.

**Comment by Violet-CLM** [comment]
FWIW you can already do this by holding Tab.

**Comment by Violet-CLM** [comment]
Well, it's a JCS feature. Holding tab is always how it's worked. Not everyone has a middle button.
