### ISSUE TITLE
Auto-packer feature

### ISSUE THREAD

**Issue by onetruepurple** [Violet-CLM/MLLE#18]
Just the one level for HH17 I'm making requires the following files to work properly:

- 7 additional tilesets
- 4 additional libraries, including the MLLE-Include library
- 2 additional .j2a files
- 1 additional .bmp file, for TrueColor.asc
- 5 additional sound samples

It took me about 5 minutes to put together everything in a zip archive for betatesting, and even then I had to kept sending files I'd forgotten. A tool that would scan the .j2as for the pragma-required files and automatically create a "release ready" zip archive would be useful.

**Comment by Violet-CLM** [comment]
You mean actually _implement_ the "Package in ZIP file" menu option that's been grayed out for six years? Good lord.
