### ISSUE TITLE
The event window can no longer turn parameter bits off

### ISSUE THREAD

**Issue by Violet-CLM** [Violet-CLM/MLLE#39]
at least in numeric boxes; haven't tried with anything else yet

**Comment by Violet-CLM** [comment]
Somehow this phenomenon seems strictly localized to the Sucker Tube event. Even other events with six parameters (Battery Check has a few) don't do this...

**Comment by Violet-CLM** [comment]
Twenty-bit events. I think SE identified a (the?) problem line.

**Comment by SirEmentaler** [comment]
> Ah, there, you bitshift a uint by 32.
bitpush may be 32 in EventForm.cs at line 543.
Solvable e.g. by changing
```cs
(0xFFFFFFFFu << bitpush)
```
> to
```cs
(uint)(0xFFFFFFFFuL << bitpush)
```
> But I'm sure you might come up with more elegant options.
