### ISSUE TITLE
"Save changes" prompt doesn't always appear

### ISSUE THREAD

**Issue by Violet-CLM** [Violet-CLM/MLLE#61]
Opening a level from the Recent Levels dropdown doesn't trigger it. Maybe other circumstances too? Try things out.

**Comment by redkevvy** [comment]
Hey Violet, I had some downtime to play and catch up on a little jj2 this weekend.  I saw this repo and made a local branch that fixes #61.  Can you grant perms so I can push that for a PR?

**Comment by SirEmentaler** [comment]
You should be able to submit a pull request with your changes if you fork the repository.

**Comment by redkevvy** [comment]
@SirEmentaler Definitely had a brain fart moment there, #72 created
