### ISSUE TITLE
Special error message when level file can't be read at all

### ISSUE THREAD

**Issue by Violet-CLM** [Violet-CLM/MLLE#9]
> [10:44 AM] Violet CLM: If you are both the host and the client on the same computer and both instances of the game are using the same copy of the level file, MLLE data will fail to load, which I blame on the operating system
> [10:46 AM] Violet CLM: You can get around that while testing stuff by having two Jazz2.exe files in different folders and making sure the client's AdditionalFileFolders entry in plus.ini doesn't include the server's directory
> [10:47 AM] Violet CLM: (because then the client executable will have to download the level and will thereafter use a version in the client folder's cache folder)
> [10:48 AM] Violet CLM: I should add that to the list of error messages MLLE-Include can show, since 'MLLE::Setup: Level file does not contain any additional data!' is technically correct but doesn't really convey the issue at hand

**Comment by SirEmentaler** [comment]
> [10:44 AM] Violet CLM: If you are both the host and the client on the same computer and both instances of the game are using the same copy of the level file, MLLE data will fail to load, which I blame on the operating system

Due to security concerns, JJ2+ limits what files `jjSTREAM` can open client-side to .asdat files, `#pragma` required files, and files in the cache directory. It may be worth looking into extending this list.
