### ISSUE TITLE
A blacklist tileset-menu so they don't show up in the selectable dropdown menu

### ISSUE THREAD

**Issue by FawFuLJJ2** [Violet-CLM/MLLE#97]
With >1000 tilesets in my JJ2 folder it gets very painful navigating through a dropdown menu to get inspiration for tileset mashups. 

After a week of painfully moving tilesets to my cache folder manually (x different versions of bad JJ1 conversions, palette edits and 30 ShakerNL mario tilesets further) I can't recommend it to anyone. But my dropdown is finally not a mess anymore which I'm happy about. I managed to move around half of them. And eventhough unlikely, i might get a tileset 'can't find tileset' error when looking at levels in MLLE. That's the cost I'm currently willing to pay.

I feel like this could use an enhancement, so opening levels still work, but you can also keep a good MLLE work environment. Maybe something like: Levels opened with blacklisted tilesets are greyed out, but still work. The selected tileset is in grey text so you can see you've blacklisted it before. Somewhere in the properties - tab an option that opens up a window where you can blacklist tilesets, mby with <-  -> buttons to move them . Maybe this can also include an overview of what .j2t filename corresponds with what tileset name.

**Comment by blurredd** [comment]
I would go with showing only the 10 most recently used tilesets as well as pinned tilesets (with the option of manually removing any tileset from the drop-down) in combination with a simple search tool filtering by tileset name and/or filename.

**Comment by Violet-CLM** [comment]
Closed by #108
